lib/cli.js
=> add back non-camelCased flags for `skip-install` and `skip-test`

lib/routes/install.js, package.json, test/route-install.js
solves https://github.com/yeoman/yo/issues/261
=> get blacklist from yeoman.io

.jshintrc
Based on [latest default options](https://github.com/jshint/jshint/blob/235f26733eb003116e5bc013b4678442ee441a25/examples/.jshintrc)
=> Update JSHint options

readme.md
And renamed "sponsors" to "backers"
=> Added the backers badge

lib/router.js, test/helpers.js, test/router.js
This PR contains a fix for #444.
I first covered the existing coding with unit tests, then added the failing test case and the corresponding fix. I also added a new helper function that creates a fake for the `read-pkg-up` module that I use in the tests.
What do you think?
=> Fix main generator detection pattern

.eslintrc, lib/routes/install.js, package.json, test/route-clear-config.js, test/route-help.js, test/route-home.js, test/route-install.js, test/route-update.js
=> Drop `pinkie-promise`.

.github/PULL_REQUEST_TEMPLATE.md
Fixing template as this is supposed to be a checklist?
=> Fix template

lib/routes/install.js, package.json
Bump `got` from `^5.0.0` to `^6.7.1`.
I would like to make sure that the way I switched from a callback to a promise is proper.
=> Bump `got`.

package.json
Bump `read-pkg-up` from `^1.0.1` to `^2.0.0`.
No.
=> Bump `read-pkg-up`.

package.json
Bump `inquirer` from `^1.0.2` to `^3.0.1`.
No.
=> Bump `inquirer`.

lib/routes/exit.js, package.json
Use `string.prototype.repeat` over `repeating`.
No.
=> Use `string.prototype.repeat` over `repeating`.

lib/router.js, package.json, test/route-home.js, test/route-install.js
Bump `lodash` from `^3.2.0` to `^4.17.4`.
No.
=> Bump `lodash`.

lib/cli.js
- [x ] Enhancement
Included a check in cli.js to determine if first cli arg was prefixed with 'generator-' and log a helpful message if so.
First time OSS contributor so any comments/tips would be appreciated!
=> Fix for 'generator-' prefix in cli

lib/usage.txt, readme.md
Added documentation for local generators. #546 
N/A
=> Add documentation for local generators

lib/routes/home.js
Fixes https://github.com/yeoman/yo/issues/540
- added an isString check on `name` variable to ensure it is a string so that it doesn't fail on the .split.
Used lodash since it's already a dependency. 
https://github.com/bjdelro/yo/blob/ec37d54f8dd6ab50d77d2deeaab26db599e77581/lib/routes/home.js#L58
=> Fixes ParseError

LICENSE
The README already mentions the BSD 2-Clause license; this PR just adds the file to the repo.
=> Add BSD 2-Clause license

package.json, test/completion.js
Fixing unit tests:
- Some of the unit tests are taking more than 2 seconds (default `--timeout` value for `mocha`). So increase this value to 10 seconds after check that some of the tests are eventually taking 9 seconds in local environment (macOS and NodeJS docker container - alpine based) is a solution since check the reasons will take more time and avoid other contributors to have the same issue (on Travis-CI is taking ~3 seconds);
- Removing cache when running tests for `yo completion`. This is required because the tests are flaky, based on the last travis-ci statuses on `master` branch;
=> Fixing unit tests

package-lock.json, package.json, test/global-config.js, test/route-clear-config.js, test/route-help.js, test/route-home.js, test/route-install.js, test/route-update.js
Upgrade SinonJS to v6 and, since some of the old methods were deprecated, some code changes were applied to support this version
=> chore: bumping sinon to 6.1.3

lib/routes/install.js, package-lock.json, package.json, test/cli.js, test/completion.js, test/global-config.js, test/route-home.js, test/route-install.js, test/route-run.js, test/router.js
- Bump [xo@0.24.0](https://github.com/xojs/xo)
- Remove unused `eslint-disable`
- Use `assert.strictEqual` instead of `assert.equal`
- Use `assert.deepStrictEqual` instead of `assert.deepEqual`
Nothing
=> Bump xo@0.24.0

lib/cli.js, lib/usage.txt, package-lock.json, package.json, readme.md, test/cli.js, test/completion.js, test/helpers.js
Added the `--local-only` CLI option, discussed [here](https://github.com/yeoman/environment/pull/113)
Nothing major except some changes to sinon usage in tests to match the new `env#lookup` behavior, where the callback arg might be the first or second arg.
=> Add --local-only option

package-lock.json, package.json
=> Bump yeoman-environment to 3.3.0

.github/workflows/ci.yml
=> Add support to node 16.

package-lock.json, package.json
=> Bump yeoman-environment to 3.4.0.

package-lock.json, package.json
=> Set xo to 0.38.0

lib/cli.js, package.json, test/route-clear-config.js
=> Fix tests and revert meow to 5.0.0.

package-lock.json, package.json
I upgraded `yeoman-environment`. Closes #797.
=> chore: upgrade `yeoman-environment`

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/scorecard.yml
- Pin dependencies and add explicit permissions in the ci workflow (c4bd5f9) 
- Add [CodeQL](https://codeql.github.com/) workflow (49daf27)
- Add [OSSF Scorecard](https://github.com/marketplace/actions/ossf-scorecard-action) reporting workflow (ba9b8f2)
- Add [dependency-review tool](https://github.com/marketplace/actions/dependency-review) workflow (af62f1b)
Related to https://github.com/yeoman/.github/issues/1
- c4bd5f9 ci: pin dependencies and explicit permissions in the pipeline by @UlisesGascon
- 49daf27 feat: add CodeQL by @UlisesGascon
- ba9b8f2 feat: add OSSF Scorecard by @UlisesGascon
- af62f1b feat: add dependency-review tool by @UlisesGascon
=> Security improvements

.travis.yml
Currently we use GitHub Actions for CI
=> Remove travis

lib/cli.js, lib/completion/completer.cjs, lib/completion/index.cjs, lib/completion/tabtab.cjs, lib/router.js, lib/routes/clear-config.js, lib/routes/exit.js, lib/routes/help.js, lib/routes/home.js, lib/routes/install.js, lib/routes/run.js, lib/routes/update.js, lib/utils/global-config.js, lib/utils/node-shims.js, lib/utils/project-package.js, package-lock.json, package.json, test/cli.js, test/completion.js, test/global-config.js, test/helpers.js, test/route-clear-config.js, test/route-exit.js, test/route-help.js, test/route-home.js, test/route-install.js, test/route-run.js, test/route-update.js, test/router.js
=> bump xo to v0.60.0

test/route-install.js
=> skip nock related tests on macos

lib/routes/install.js, package-lock.json, package.json
=> drop async dependency

test/route-clear-config.js, test/route-help.js, test/route-home.js, test/route-install.js, test/route-update.js, test/router.js
Tests with callback usually times out instead of failing with error message.
Promisify to facilitate.
=> promisify route tests

package-lock.json, package.json, test/route-clear-config.js, test/route-help.js, test/route-home.js, test/route-install.js, test/route-update.js
=> chore: rework test to use TestAdapter

.github/workflows/ci.yml, test/route-update.js
=> chore: fix test with node 24

lib/router.js, lib/routes/clear-config.js, lib/routes/home.js, package-lock.json, package.json
=> chore: drop direct dependency on inquirer

package-lock.json, package.json
=> chore: bump yeoman-doctor
